apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: auth-routes
spec:
  routes:
    - kind: Rule
      match: PathPrefix(`/auth`) # Запросы с префиксом /auth отправляем в auth-service
      services:
        - name: {{ include "app.auth" .}}
          namespace: default
          port: 80
      middlewares:
        - name: strip-auth-prefix # Убираем префикс из пути, чтобы запросы шли на корень сервиса
          namespace: default
    - kind: Rule
      match: PathPrefix(`/notification`)
      services:
        - name: {{ include "app.notification" . }}
          namespace: default
          port: 80
      middlewares:
        - name: auth # Включаем forward-auth
          namespace: default
    - kind: Rule
      match: PathPrefix(`/order`)
      services:
        - name: {{ include "app.order" . }}
          namespace: default
          port: 80
      middlewares:
        - name: auth # Включаем forward-auth
          namespace: default
    - kind: Rule
      match: PathPrefix(`/`)
      priority: 10 # Добавляем маршрут с большим приоритетом, чтобы эти натсройки применились поверх предыдущих
      services:
        - name: {{ include "app.billing" . }}
          namespace: default
          port: 80
      middlewares:
        - name: auth # Включаем forward-auth
          namespace: default