apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.billing" . }}
  labels:
    name: {{ include "app.billing" . }}
    {{- include "app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 0 # Default to 10 if not specified
  selector:
    matchLabels:
      name: {{ include "app.billing" . }}
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        name: {{ include "app.billing" . }}
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.billingService.image.repository }}:{{ .Values.billingService.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.billingService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ template "app.fullname" . }}-assets
              mountPath: /var/www/app
          env:
          {{- range $key, $value := .Values.billingService.env }}
            - name: {{ $value.name }}
              valueFrom:
                secretKeyRef:
                  key: {{ $value.key }}
                  name: {{- include "app.secret" $ | indent 4 }}
          {{- end }}
        - name: nginx
          image: nginx:alpine
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          volumeMounts:
          - name: {{ template "app.fullname" . }}-nginx
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
          - name: {{ template "app.fullname" . }}-assets
            mountPath: /var/www/app
      volumes:
        - name: {{ template "app.fullname" . }}-nginx
          configMap:
            name: {{ template "app.fullname" . }}-nginx
        {{- if .Values.billingService.develop.enabled }}
        - name: {{ template "app.fullname" . }}-assets
          hostPath:
            path: {{.Values.billingService.develop.pwd}}
        {{- else }}
        - name: {{ template "app.fullname" . }}-assets
          emptyDir: { }
        {{ end }}
      {{- if not .Values.billingService.develop.enabled }}
      initContainers:
        - name: {{ template "app.fullname" . }}-assets
          image: "{{ .Values.billingService.image.repository }}:{{ .Values.billingService.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.billingService.image.pullPolicy }}
          command: ['sh', '-c', "cp -rT /tmp/app /var/www/app"]
          volumeMounts:
            - name: {{ template "app.fullname" . }}-assets
              mountPath: /var/www/app/
      {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}